// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzcnapnirwqagdbmpdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xemNuYXBuaXJ3cWFnZGJtcGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDAyMDQsImV4cCI6MjA2NjQxNjIwNH0.MBA-fRMf8jmxJhW9R50h7mBoYKs4LEWW6h0TW5fqZWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);